baseURL = 'https://gvnn.vn/'
theme = 'hugo-theme-walden'

defaultContentLanguage = 'en'

[params]
    themestyle = 'blue'
    showLangSwitch = true

[taxonomies]
    category = 'categories'
    tag = 'tags'
    series = 'series'

# 用于渲染的参数
[markup]
    defaultMarkdownHandler = 'goldmark'
    [markup.goldmark.renderer]
        unsafe = true

[module]
    [module.hugoVersion]
        extended = true
        min = "0.149.0"
